### ISSUE TITLE
Sorry again... 

### ISSUE THREAD

**Issue by DrMichael** [opendreambox/enigma2-plugins#19]
Hi,

I am afraid, I screwed it up again. Can someone please revert the merge: https://github.com/opendreambox/enigma2-plugins/commit/70b3ba04035998b89b661b443acaa0bca0bb0797 ?

DrMichael

**Comment by svenh0** [comment]
oh, yes.
I missing now this commits:
- Sven H - Elektro: Version 3.4.5c 
- Dr.Best - [MovieSelectionQuickButton] make sure that "Home"-Butto... 
- dre - EPGSearch: improvements on texts to make them better... 
- reichi - skipintro: make plugin desc translatable 
- reichi - add "SkipIntro" plugin 
- reichi - webinterface: append subdirectories to the end of ...

**Comment by DrMichael** [comment]
How would I revert a commit?

**Comment by svenh0** [comment]
I don't know.
But this merge-commit is also not show in the commits-list ?!?
Here i also can't see the merge-commit:
http://git.opendreambox.org/?p=enigma2-plugins.git;a=summary

**Comment by DrMichael** [comment]
Hmmm, no, that is of 22.10.2018...

**Comment by DrMichael** [comment]
Hmmm, no, that is of 22.10.2018...
Perhaps someone already reverted it?

**Comment by dhwz** [comment]
DrMichael in Zukunft einfach erst das lokale Git synchronisieren bevor du etwas zu Github hochschiebst.

**Comment by DrMichael** [comment]
Habe doch vorher einen Pull gemacht?!?!

**Comment by dhwz** [comment]
Ich versteh eher nicht wie du es geschafft hast die Commit Historie zu löschen, daher geht jetzt auch kein Revert mehr die Commits sind nicht mehr da. Die Änderungen davon sind jetzt in deinem enthalten.

**Comment by dhwz** [comment]
Mal kurz schauen ob ich den Stand noch hab dann kann ich es wieder reparieren.

**Comment by dhwz** [comment]
Deine Commit ist jetzt weg, kannst du das Git nochmal neu pullen und dann erst deine Änderung einfügen und neu committen.

**Comment by dhwz** [comment]
@svenh0 
Oder so, wobei ich nicht weiß wie das dann geht wenn er in den 4.0 Branch committen will.

**Comment by DrMichael** [comment]
in 4.0 committen ist ja nicht das Problem. aber den Commit dann per CherryPick in den master...

Habe jetzt Pull und Fetch gemacht, aber meine Änderungen und der Merge sind immer noch da.

**Comment by drbest2** [comment]
Ich hab das jetzt mal für Dich übernommen.
Ich kenne mich mit den ganzen Windows/MAC Tools nicht aus, ich bin ein reiner Consolen-Mensch unter Linux mit GIT:

git checkout master
git pull
git cherry-pick 72fb64d4424843554d4d748c8ee81be
git push

Das wärs auch schon.

**Comment by DrMichael** [comment]
Exakt das habe ich ja gemacht... Denke ich.

**Comment by DrMichael** [comment]
Ah, DrBest war so frei, meine Änderungen in master zu übernehmen...

Habe das Repo jetzt komplett neu geholt, sieht gut aus.
