### ISSUE TITLE
Satipclient is not working with 2 physical tuners on DM920

### ISSUE THREAD

**Issue by palik42** [opendreambox/enigma2-plugins#20]
Hello,
I found bug or missing implementation. I don't know if problem is in plugin or if it is in DreamOS..
I have two tuners in DM920 - BCM45208 and BCM45308 ... when I disconnected BCM45308 satip start working. But when I have both tuners in DM satip is not working. As server I used Minisatip 8.. If you want see logs here are some.. https://minisatip.org/forum/viewtopic.php?f=5&t=542

**Comment by dhwz** [comment]
See https://dreambox.de/board/index.php?thread/24494-bug-missing-implementation-in-satipclient-dreamos-for-dm920/
