### ISSUE TITLE
Git error... Please revert the two merges...

### ISSUE THREAD

**Issue by DrMichael** [opendreambox/enigma2-plugins#27]
Please revert the commits 53080ee1c7eaacc711cdbbcf0d43899b924030e9 and b346f1f4e63f5b340528fdc6ca3b892e1390f9fa.

Again screwed up the commits. Sorry.

**Comment by dhwz** [comment]
Was passt denn nicht? Der merge commit macht nichts kaputt wenn es dir nur darum geht.

**Comment by DrMichael** [comment]
Oh, gut. Schock, ich dachte, ich hätte andere Plugins kaputt gemacht...

**Comment by amonzner** [comment]
Hi,

 am Montag, 25. Januar 2021 um 18:34 schrieb DrMichael:
> Oh, gut. Schock, ich dachte, ich hätte andere Plugins kaputt gemacht...

Ich habs aber nun schon Rückgängig gemacht ;)

cya

**Comment by svenh0** [comment]
Dadurch ist jetzt auch das commit für movietagger weg, oder?

**Comment by dhwz** [comment]
Ja hat er, ich hab meinen Stand wiederhergestellt, jetzt fehlen die Commits von @drecomx und die von @DrMichael

**Comment by DrMichael** [comment]
Könnte mir jemand den Gefallen tun und meine Änderungen in 4.0 in master nachziehen? (Idealerweise auch die Revision Number Changes, muss aber nicht unbedingt). Ich traue mich an master nicht mehr ran... :-)

**Comment by svenh0** [comment]
Womit hast du den commit gemacht?
Ich nutze nur noch die Weboberfläche von github im Browser. 
Da lade ich die geänderten Files per Drag & Drop hoch und gebe den commit-Text an. 
Die git-Clients auf dem PC waren mir auch zu aufregend (jeder commit war mit Angst verbunden).

**Comment by dhwz** [comment]
@DrMichael 
schau bitte nochmal nach ob das jetzt so passt :)

**Comment by drecomx** [comment]
Ich nutze SourceTree. Da habe ich alle Branches ausgecheckt, die ich brauche. Die geänderten Dateien commite und pushe ich nach master. Dann wechsle ich auf den Branch 4.3 und klicke mit der rechten Maustaste auf den commit aus master und sage Rosinen herauspicken. Die untere Checkbox (commit nach merge oder so ähnlich) anwählen. Dann noch push und erledigt. 

Zu den Commits von mir: die waren wohl am Abend wieder da. Aber hab eh noch was gefixt und der Stand sollte jetzt wieder passen.

**Comment by DrMichael** [comment]
> @DrMichael
> schau bitte nochmal nach ob das jetzt so passt :)

Sieht sehr gut aus. :-)

> Und was ist eigentlich mit 4.3, dort fehlen einige deiner letzten Änderungen, kannst dort bitte mal den aktuellen Stand comitten.
> 4.3 ist OE2.5

Normalerweise mache ich die Änderungen in 4.0 und cherry pick dann in master. Soll ich statt 4.0 lieber 4.3 nehmen?

**Comment by dhwz** [comment]
Also 4.0 wird bei Dream eigentlich gar nicht mehr benutzt.
master = OE2.6
4.3 = OE2.5
Das sind die zwei wichtigsten und noch aktuellen Branches.

**Comment by DrMichael** [comment]
Mal zum Verständnis, OE2.6 hat Python3, OE2.5 Python2?

**Comment by dhwz** [comment]
Nein keines davon ist aktuell Python3.
OE2.6 ist für die Amlogic Boxen (Dreambox One/Two)
OE2.5 ist für die Broadcom Boxen (900, 920, 820, 7080)

**Comment by DrMichael** [comment]
> Am einfachsten wäre es du machst einen commit mit allen Files des aktuellen Standes in den 4.3 Branch, oder du schickst mir die Files wenn du Angst hast etwas kaputt zu machen.

Also, ich commite jetzt mal meinen STand (wie in 4.0) nach 4.3. Bitte mal prüfen danach. Danke.

**Comment by dhwz** [comment]
Ok schaut gut aus, danke!

**Comment by DrMichael** [comment]
Yippie. :-)
